config/routes.rb
Rails.application.routes.draw do
  # verb 'path', to: 'controller#action', as: :nickname

  # both below are the same
  get "/", to: "flats#index", as: :flats
  # root to: "flats#index", as: :flats

  get "/flats/:id", to: "flats#show", as: :flat

end


# HTTP AND AJAX LECTURE
# Restful (REST) pattern
# VERB - ACTION
# GET - READ
# POST - CREATE
# PUT/PATCH - UPDATE
# DELETE - DESTROY

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  def index
    @flats = fetch_flats
  end

  def show
    flats = fetch_flats

    id = params['id'].to_i

    @flat = flats.find { |flat| flat['id'] == id }
  end

  private

  def fetch_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    JSON.parse(open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>My Lovely Flats - A Poor Airbnb Clone</h1>

<ul style='display: grid; grid-template-columns: 1fr 1fr 1fr; grid-gap: 16px;'>
  <% @flats.each do |flat| %>
    <li>

      <%# we can create a link like this %>
      <%# link_to flat_path(flat['id']) do %>
      <%# link_to "flats/#{flat['id']}" do %>
        <%#= flat['name'] %> <%# flat['price'] %> <%# flat['priceCurrency'] %>
      <%# end %>
      <%# this is the best practice 🆙 %>

      <%# we can create a link like that %>
      <a href="flats/<%= flat['id'] %>">
        <%= flat['name'] %> | <%= flat['price'] %> <%= flat['priceCurrency'] %>
      </a>

      <img src="<%= flat['imageUrl'] %>" alt="" style="width: 256px;">
    </li>
  <% end %>
</ul>

<%# 
  {"id"=>211, 
  "name"=>"Bohemian and Chic in Paris", 
  "imageUrl"=>"https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/images/flat6.jpg", 
  "price"=>90, 
  "priceCurrency"=>"EUR", 
  "lat"=>48.827855, 
  "lng"=>2.350774} 
%>

app/views/flats/show.html.erb
<h2>Welcome to <%= @flat['name'] %></h2>

<p><%= @flat %></p>

<%= link_to 'Back', '/' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic738</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>